### ISSUE TITLE
Consider providing a bridge to JuicyPixels for IO

### ISSUE THREAD

**Issue by cies** [RaphaelJ/friday#12]
That would give a very attractive all-in-Haskell solution for the basic image processing needs of most web applications.

No need to install IMagick or similar, or a C library -- just `cabal install` all the way :)

**Comment by RaphaelJ** [comment]
It's the most requested feature and it's is on the way !

However, I'm working on my Master's thesis full time and it's difficult to give time the project these days.

**Comment by cies** [comment]
That's great. By no means trying to push agenda :)

Wishing you all the best for your thesis...

**Comment by sdroege** [comment]
For combining JuicyPixels and Friday, isn't it enough to just either a) map the raw image vectors to the appropriate pixel type of the other library, or b) even just unsafeCoerce the vectors as long as the representations of the pixel values are the same?

**Comment by cies** [comment]
@sdroege I would not dare to say. I guess the internal representations are not the same, so a map would most likely be needed at first. Maybe a common internal representation could be agreed on at a later point, this would make interop a lot easier and faster.

But at first I think a all-Haskell solution for basic image conversions and transformations would be totally awesome. For my usecases it would not matter much if it is significantly slower then breaking out into C-libs or programs like ImageMagik.

**Comment by TomMD** [comment]
It appears this can be done using `unsafeCoerce` of the Storable vectors (observe Grey can be `coerce`d to the Pixel8 type safely, RGB and PixelRGB have the same representation, and same for RGBA).  I'll give it a go tonight (assuming I find the time) and put the results in a feature branch on my fork.  Hopefully we'll make a system that works well with ffmpeg-light.

**Comment by cies** [comment]
I'm really curious how it went (if you found the time)... :)

**Comment by TomMD** [comment]
@cies It works flawlessly.  I'm going to make a friday-juicypixels package (tempted to call it juicy-friday, but the name `friday-devil` sets a precident).  It should hit my github in some form tonight but that form will be horribly primitive.

**Comment by cies** [comment]
Wow. Good to hear, thanks!

**Comment by sdroege** [comment]
Yay, good work :) From looking at the code I was expecting the pixel representations to be compatible (for most formats, IIRC Friday has no support for YUV-based pixel formats?) but got no time yet to actually try it.

Can you also put some small examples into your GIT repository, once it's there?

**Comment by cies** [comment]
Had a look at the code. Looks so simple :)  I do hope that, and guess @TomMD you intends to, remove the dependency on `friday-devil`. As that lib needs DeviL C lib to compile.

**Comment by TomMD** [comment]
@RaphaelJ This, and other basically completed, tasks have been laying around.  I'm hoping your masters ended well along with the typical move/find job/cook food issues that follow.  If you're busy then I'd be happy to handle this repo for a few months - close this issue, accept my pull, push changes to hackage / Friday including the contours work and notes about friday-juicypixels.  Up to you.

**Comment by RaphaelJ** [comment]
Hi Tom,

Yeah, the thesis went well. But now I'm working for a early stage startup and I have even less time to spend on `friday` (I'd be so glad to have more than 24h in a day ...).

I did had you as a collaborator on `friday` related repositories. I'd be pleased to have you maintaining the project for some time !

Regards,

**Comment by TomMD** [comment]
@RaphaelJ  Thanks!

@cies I'm closing this in light of TomMD/friday-juicypixels  re-open if you feel the issues still isn't resolved.
