### ISSUE TITLE
Warnings when compiling my code using the Friday library: "match_co: needs more cases"

### ISSUE THREAD

**Issue by bamos** [RaphaelJ/friday#15]
Hi, sorry if this is a simple question (I'm new to Haskell), but
I'm using Friday in an application for some simple
image operations ([source](https://github.com/bamos/augment/blob/6bbb6f1dd1f709b591ed7338b67b0afc6636fc7d/Augment.hs)).

Did I do something wrong to cause the following warning message when compiling? Full build info is available at https://travis-ci.org/bamos/augment/builds/62451721

```
match_co: needs more cases
    friday-0.2.1.2:Vision.Image.Type.TFCo:R:ImagePixelManifest{tc r3AS}[0]
      (Sym
         (friday-0.2.1.2:Vision.Image.Type.TFCo:R:FromFunctionPixelManifest{tc r3B9}[0]
            <friday-0.2.1.2:Vision.Image.RGB.Type.RGBPixel{tc ray}>_N))
```

**Comment by RaphaelJ** [comment]
It happens when GHC fails to SPECIALIZE something, for a reason I don't know. It doesn't hurt anything except, maybe, performances. 

I should have some time to give to Friday next week. I'll take a look at this issue. Stay tuned!
