### ISSUE TITLE
Q: indication from creating an image painting a rectangle with specified rgb

### ISSUE THREAD

**Issue by gsscoder** [RaphaelJ/friday#20]
Hi,
thansk for sharing this very helpful library, samples and additional documentation. I'm new to Haskell and even new to this library (since after some research I think this is the more suitable for the thing I'm trying to do).

What I'm trying to do is translating this **F#** snippet for Random Art: http://fssnip.net/si.

To implement the function `draw` at line 122, I must be able to:
- set up an image of defined height and width
- draw a rectangle with coordinates (x,y) and its height/width with the specified R,G,B

Can I have some indications for accomplish this task and put me on right direction, if possible.

Thanks, Giacomo.

P.S.: finished the porting, I obviously share my work.

**Comment by TomMD** [comment]
@gsscoder For drawing, consider using the `generate` function.  For example, the untested psuedo-code below:

```
draw (rows,columns) (y0,x0) (height,width) =
   generate (Z :. rows :. columns) (\pnt -> if inRectangle pnt then color else background)
 where
  inRectangle (x,y) = x >= x0 && x <= x0+width && y >= y0 && y <= y0+height
```

**Comment by gsscoder** [comment]
@TomMD, thanks for suggestion, I'll try to put it practice. :)

Your example tries to _mimic_ .NET the call to FillRectangle w/ SolidBrush in F# snippet, right?

Most of library sample start follows this flow: load picture -> transform -> save.

I will appreciate a sample (just 1 line of code) where a blank `Image` is initialized with specific width / height...

Thanks.

**Comment by gsscoder** [comment]
I've waited and it worked!
```zsh
==> make install
🍺  /usr/local/Cellar/gcc49/4.9.3: 1138 files, 165M, built in 59.1 minutes
```
I was able to install `devil` package.
```zsh
➜  ~  brew install devil
==> Downloading https://downloads.sourceforge.net/project/openil/DevIL/1.7.8/DevIL-1.7.8.tar.gz
==> Downloading from http://heanet.dl.sourceforge.net/project/openil/DevIL/1.7.8/DevIL-1.7.8.tar.gz
######################################################################## 100,0%
==> Patching
patching file src-ILU/ilur/ilur.c
==> ./configure --prefix=/usr/local/Cellar/devil/1.7.8_1 --enable-ILU --enable-ILUT
==> make install
🍺  /usr/local/Cellar/devil/1.7.8_1: 23 files, 1,4M, built in 79 seconds
```
Now I'm trying to figure why `cabal friday-devil` still doesn't work, but this is not the place.

Thanks everyone! Really. :)

**Comment by gsscoder** [comment]
Solved, also the latest point. If can be helpful for others:
```zsh
➜  ~  cabal install friday-devil --extra-include-dirs=/usr/local/Cellar/devil/1.7.8_1/include/  --extra-lib-dirs=/usr/local/Cellar/devil/1.7.8_1/lib/
Resolving dependencies...
Configuring friday-devil-0.1.1.1...
Building friday-devil-0.1.1.1...
Installed friday-devil-0.1.1.1
Updating documentation index
/Users/giacomo/Library/Haskell/share/doc/x86_64-osx-ghc-7.8.3/index.html
```
Just tell cabal where include and lib are located.

**Comment by gsscoder** [comment]
Sorry, don't take into account latest two post. I had this other browser window open on: https://github.com/Homebrew/homebrew/issues/43824

**Comment by TomMD** [comment]
You desiring a blank image suggests you want it to be mutable, right?  Are you aware that mutability is a different beast in Haskell than many other languages?

**Comment by gsscoder** [comment]
@TomMD,
I think that also initialization can be described functionally.
```
--psudocode:
let blank = newImage heigth width
let modified = draw blank \(x,y,color) -> generate x y color
```
Am I wrong?

**Comment by RaphaelJ** [comment]
As @TomMD said, images in friday are immutable. That means that you create a new image every time you want to draw something.

The library also provides a way to use mutable images (https://hackage.haskell.org/package/friday-0.2.2.0/docs/Vision-Image-Mutable.html). There is currently no drawing function, however.

**Comment by gsscoder** [comment]
@RaphaelJ,
I've a too low knowledge of API for being clear of what I really need.

Thanks for support! I'll back after being more confident with the library.
